/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as DuasRouteImport } from './routes/duas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuranIndexRouteImport } from './routes/quran.index'
import { Route as QuranSurahIdRouteImport } from './routes/quran.$surahId'

const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const DuasRoute = DuasRouteImport.update({
  id: '/duas',
  path: '/duas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranIndexRoute = QuranIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuranRoute,
} as any)
const QuranSurahIdRoute = QuranSurahIdRouteImport.update({
  id: '/$surahId',
  path: '/$surahId',
  getParentRoute: () => QuranRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/duas': typeof DuasRoute
  '/quran': typeof QuranRouteWithChildren
  '/quran/$surahId': typeof QuranSurahIdRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/duas': typeof DuasRoute
  '/quran/$surahId': typeof QuranSurahIdRoute
  '/quran': typeof QuranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/duas': typeof DuasRoute
  '/quran': typeof QuranRouteWithChildren
  '/quran/$surahId': typeof QuranSurahIdRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/duas' | '/quran' | '/quran/$surahId' | '/quran/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/duas' | '/quran/$surahId' | '/quran'
  id: '__root__' | '/' | '/duas' | '/quran' | '/quran/$surahId' | '/quran/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DuasRoute: typeof DuasRoute
  QuranRoute: typeof QuranRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duas': {
      id: '/duas'
      path: '/duas'
      fullPath: '/duas'
      preLoaderRoute: typeof DuasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/': {
      id: '/quran/'
      path: '/'
      fullPath: '/quran/'
      preLoaderRoute: typeof QuranIndexRouteImport
      parentRoute: typeof QuranRoute
    }
    '/quran/$surahId': {
      id: '/quran/$surahId'
      path: '/$surahId'
      fullPath: '/quran/$surahId'
      preLoaderRoute: typeof QuranSurahIdRouteImport
      parentRoute: typeof QuranRoute
    }
  }
}

interface QuranRouteChildren {
  QuranSurahIdRoute: typeof QuranSurahIdRoute
  QuranIndexRoute: typeof QuranIndexRoute
}

const QuranRouteChildren: QuranRouteChildren = {
  QuranSurahIdRoute: QuranSurahIdRoute,
  QuranIndexRoute: QuranIndexRoute,
}

const QuranRouteWithChildren = QuranRoute._addFileChildren(QuranRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DuasRoute: DuasRoute,
  QuranRoute: QuranRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
